name: run

on:
  pull_request:
  push:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -e .
      - name: Prepare repo
        run: |
          python -m hgl.init --repo repo
      - name: Archive repo
        uses: actions/upload-artifact@v2
        with:
          name: repo
          path: |
            repo.tar

  test:
    needs: init
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -e .[test]
    - uses: actions/download-artifact@v2
      with:
        name: repo
    - name: Test with pytest
      run: |
        pytest -n logical --junitxml=test-results.xml
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v2
      with:
        report_paths: test-results.xml
